DROP TABLE IF EXISTS hole;

CREATE TABLE hole (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  latitude VARCHAR(40) NOT NULL,
  longitude VARCHAR(40) NOT NULL,
  obs VARCHAR(200),
  fixed TINYINT(1) DEFAULT 0,
  foto_id VARCHAR(90) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;